#!/bin/bash
SUFFIX=$(date +%s)
USERNAME="user_$SUFFIX"
EMAIL="user_$SUFFIX@example.com"
echo ">>> 1. Creating user: $USERNAME"

curl -s -X POST http://localhost:8080/api/auth/signup \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"$USERNAME\", \"password\": \"password123\", \"email\": \"$EMAIL\", \"nickname\": \"Nick_$SUFFIX\"}"
echo ""

echo ">>> 2. Logging in..."
LOGIN_RES=$(curl -s -X POST http://localhost:8080/api/auth/login \
  -H "Content-Type: application/json" \
  -d "{\"username\": \"$USERNAME\", \"password\": \"password123\"}")
echo "Login Res: $LOGIN_RES"

TOKEN=$(echo $LOGIN_RES | python3 -c "import sys, json; print(json.load(sys.stdin)['accessToken'])")
echo "Token: $TOKEN"

if [ -z "$TOKEN" ]; then
  echo "Login failed, exiting."
  exit 1
fi

echo ">>> 3. Creating Magazine (Internal)..."
curl -s -X POST http://localhost:8080/api/internal/magazine \
  -H "Content-Type: application/json" \
  -H "X-Internal-Key: mine-secret-key-1234" \
  -d "{\"title\": \"Test Magazine $SUFFIX\", \"introduction\": \"Generated by Test Script\", \"cover_image_url\": \"http://example.com/cover.jpg\", \"user_email\": \"$USERNAME\", \"sections\": [{\"heading\": \"Sec 1\", \"content\": \"Content 1\", \"image_url\": \"http://img.com/1.jpg\", \"layout_hint\": \"full\"}]}"
echo ""

echo ">>> 4. Listing My Magazines..."
curl -s -X GET "http://localhost:8080/api/magazines?page=0&size=10" \
  -H "Authorization: Bearer $TOKEN"
echo ""
